/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package validasi.form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import validasi.SQLiteConnection;
import validasi.TabelImport;

/**
 *
 * @author faheem
 */
public class SettingTableKey extends javax.swing.JFrame {
    private Connection conn;
    /**
     * Creates new form SettingTableKey
     */
    public SettingTableKey() {
        initComponents();
        DefaultListModel defModel = new DefaultListModel();
        jList2.setModel(defModel);
        
        cmbTable.removeAllItems();
        conn = new SQLiteConnection().getConn();
        List<String> a = new TabelImport().getTableList();
        for (int i = 0; i < a.size(); i++) {
            cmbTable.addItem(a.get(i));
        }
        jList1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                btnRight.setEnabled(jList1.getSelectedIndex()>=0);
            }
        });
        jList2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                btnLeft.setEnabled(jList2.getSelectedIndex()>=0);
            }
        });
    }

    private void addColumn(String k){
        try{
            int i=conn.createStatement().executeUpdate("insert into c_table_key (table_name, column_name) "
                    + "values('"+cmbTable.getSelectedItem().toString()+"', '"+k+"')");
            if(i>0){
                showTableKey(k);
            }
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }
    
    private void removeColumn(String k){
        try{
            int i=conn.createStatement().executeUpdate("delete from c_table_key "
                    + "where table_name='"+cmbTable.getSelectedItem().toString()+"' "
                    + "and column_name='"+k+"' ");
            if(i>0){
                showTableKey(k);
            }
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }
    
    private void showTableKey(String s){
        try{
            DefaultListModel defModel = new DefaultListModel();
            jList2.setModel(defModel);
            ResultSet rs=conn.createStatement().executeQuery("select table_name, column_name from c_table_key "
                    + "where table_name='"+cmbTable.getSelectedItem().toString()+"'");
            int i=-1;
            while(rs.next()){
                if(s.equalsIgnoreCase(rs.getString("column_name"))){
                    i=defModel.getSize()-1;
                }
                defModel.addElement(rs.getString("column_name"));
            }
            
            rs.close();
            if(i>=0){
                jList2.setSelectedIndex(i);
            }
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbTable = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setText("Daftar Kolom :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 265, 25));

        cmbTable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTable.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTableItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 10, 365, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 65, 265, 275));

        jLabel2.setText("Nama Tabel : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 100, 25));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("Kolom Kunci :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 45, 265, 25));

        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 70, 265, 275));

        btnLeft.setText("<");
        btnLeft.setEnabled(false);
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 175, 45, -1));

        btnRight.setText(">");
        btnRight.setEnabled(false);
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });
        getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 145, 45, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cmbTableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTableItemStateChanged
        if(cmbTable.getSelectedIndex()<0)
            return;
        showTableColumn("");
    }//GEN-LAST:event_cmbTableItemStateChanged

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        int iRow=jList1.getSelectedIndex();
        String colName=((DefaultListModel)jList1.getModel()).get(iRow).toString();
        ((DefaultListModel)jList2.getModel()).addElement(colName);
        addColumn(colName);
        ((DefaultListModel)jList1.getModel()).remove(iRow);
        if(iRow < jList1.getModel().getSize()){
            jList1.setSelectedIndex(iRow);
        }else{
            if(iRow >= jList1.getModel().getSize()){
                jList1.setSelectedIndex(iRow-1);
            }
        }
        jList2.setSelectedIndex(jList2.getModel().getSize()-1);
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        int iRow=jList2.getSelectedIndex();
        String colName=((DefaultListModel)jList1.getModel()).get(iRow).toString();
        ((DefaultListModel)jList2.getModel()).addElement(colName);
        removeColumn(colName);
    }//GEN-LAST:event_btnLeftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingTableKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingTableKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingTableKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingTableKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingTableKey().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JComboBox cmbTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void showTableColumn(String string) {
        try{
            int j=0;
            ResultSet rs=conn.createStatement().executeQuery("select * from "+cmbTable.getSelectedItem().toString());
            DefaultListModel defModel = new DefaultListModel();
            for(int i=0; i<rs.getMetaData().getColumnCount(); i++){
                defModel.addElement(rs.getMetaData().getColumnName(i+1));
                if(rs.getMetaData().getColumnName(i+1).equalsIgnoreCase(string)){
                    j=i;
                }
            }
            jList1.setModel(defModel);
            showTableKey("");
            if(jList1.getModel().getSize()>0){
                jList1.setSelectedIndex(j);
            }
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }
}
